### ISSUE TITLE
[BUG] Set Bonuses Sometimes Lost After Death

### ISSUE THREAD

**Issue by Rhykes** [Laike-Endaril/Set-Bonus#6] opened 2019-06-19 16:55 UTC
Tricky bug I have not been able to replicate with consistency but it happens frequently enough to be brought to your attention.

Sometimes following a death, set bonuses fail to reapply. Re-equipping gear that has them does not work, and the user needs to log out and back in for set bonuses to come back. This happens to both attributes and potion effects, and seems to happen to all sets regardless of what was equipped prior to the death.

It's possible this is a mod compatibility issue of some kind. We also use https://minecraft.curseforge.com/projects/keep-equipment which may contribute to the problem, as equipment pieces are not dropped on death and are immediately reapplied to the character upon respawning. That said, given that set bonuses continue to not function even after re-equipping them, there may be another issue at hand.

I'm not sure if there is a specific method of dying or timing with the respawn that causes this problem. It doesn't occur every death, but I've noticed it a couple times and received confused complaints. If I find any more information I'll post here.

**Comment by Laike-Endaril** [comment] 2019-06-20 00:14
Hmm, yeah, this could be a tricky one to pinpoint.  I'll have to just scrape through all my code and look for anything that could be prone to breakage, and run some general death tests.

**Comment by Rhykes** [comment] 2019-06-20 05:31
I did a little bit of testing, and I am a bit more confident that it is a mod compatibility issue with Keep Equipment. It seems to re-equip pieces directly onto your character immediately upon death (so, while you're still "dead"). I imagine this can cause some issues with set bonus applications, although I do find it very strange that unequipping the pieces doesn't fix it itself.

I'm still not 100% sure that is what it is, but it seems the most likely.

Maybe set bonuses could attempt to reapply after a few seconds after respawning?

**Comment by Laike-Endaril** [comment] 2019-06-20 05:46
This actually seems to be an issue with Set Bonus on its own.  If anything, I think Keep Equipment is the reason the issue is sometimes *not* occurring XD

I'll have to look into it further, but I've at least replicated it for now (running just Set Bonus and no other mods)

**Comment by Laike-Endaril** [comment] 2019-06-21 02:51
This should now be fixed in 1.12.2.014!  Ofc if you run into it again, please tell me.

**Closed as completed by Laike-Endaril** 2019-06-21 02:51 UTC
