### ISSUE TITLE
Mod deleting its own Potion Effects list on launch

### ISSUE THREAD

**Issue by lynaevm** [Laike-Endaril/Set-Bonus#19] opened 2020-10-09 01:32 UTC
Thank you for this mod -- I have been using it very successfully for my in-dev pack. 

But suddenly this evening I have discovered a terrible problem that I cannot understand. 

After editing the config page to add new sets, I saved and relaunched... and on relaunch it deleted the whole "Potion effects" list and none of my defined and previously-tested sets have any effects any more.  If I watch VSCode while it launches, I can even see it do it during the launch process.  Using the "undo" command will put it right back... but not effect the game.  I thought I might have made the config too long and tried deleting a few lines so it was shorter than the last time I had tested, but it had no effect.

I don't know how to recreate the problem because nothing changed between the time it was working and the time it was working except one line...

Have you encountered anything like this before? What can I do?

Attaching the config file on its own as well as the full export.
[1.12.2.009+.txt](https://github.com/Laike-Endaril/Set-Bonus/files/5352053/1.12.2.009%2B.txt)

[Costume Party Challenge-1.0.3.zip](https://github.com/Laike-Endaril/Set-Bonus/files/5352060/Costume.Party.Challenge-1.0.3.zip)

**Comment by Laike-Endaril** [comment] 2020-10-09 06:06
I haven't done any testing yet, but after a quick look at your config, I noticed that the potion bonus section is missing its closing angle bracket.  This is probably the cause.

Here's the fixed config.  Tell me if it fixes the issue:
[1.12.2.009+.txt](https://github.com/Laike-Endaril/Set-Bonus/files/5352823/1.12.2.009%2B.txt)

**Comment by lynaevm** [comment] 2020-10-09 13:14
That has fixed it -- thank you so much for your quick response and patience with my operator error :D

**Closed as completed** 2020-10-09 13:55 UTC
